### ISSUE TITLE
Not able to create Droplet with existing snapshot

### ISSUE THREAD

**Issue by vishalzanzrukia** [jeevatkm/digitalocean-api-java#69] opened 2017-07-10 10:46 UTC
Hi @jeevatkm ,

I have existing snapshot on DO and I would like to create new Droplet using that. I am able to retrieve snapshot using this api like below,
```
DigitalOceanClient client = new DigitalOceanClient("token");
Snapshots snapshots = client.getAvailableSnapshots(1, 1);
Snapshot snapshot = snapshots.getSnapshots().get(0);
System.out.println(snapshot);
```
Above gives me output like below, which is expected
`com.myjeeva.digitalocean.pojo.Snapshot@548a24a[id=24949980,name=ZivSumitTunServerTestOpenVAS,distribution=<null>,slug=<null>,availablePublic=false,regions=[blr1],createdDate=Thu May 18 15:23:34 IST 2017,minDiskSize=40,size=7.66,type=<null>,rateLimit=<null>]`

## Issue-1

Now, I am trying to create droplet using above snapshot, like below,
```
		Droplet droplet = new Droplet();
		droplet.setImage(snapshot);
		
		droplet.setName("VishalTest2Droplet");
		droplet.setStatus(DropletStatus.ACTIVE);
		droplet.setEnableBackup(Boolean.FALSE);
		
		client.createDroplet(droplet);
```

Getting below error, which is not expected because Image have already `memorySize`, `diskSize`, `Region`, `Image Id/Slug` set.
```
Exception in thread "main" java.lang.IllegalArgumentException: Missing required parameters [Name, Region Slug, Size Slug, Image Id/Slug] for create droplet.
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.createDroplet(DigitalOceanClient.java:302)
```
## Issue-2

Now, even if I try to set `Size`, `Region` manually like given below,
```
		Region region = new Region();
		region.setSlug(snapshot.getRegions().get(0));
		region.setAvailable(true);
		droplet.setRegion(region);
                droplet.setMemorySizeInMb(50 * 1024);
		droplet.setSize("512mb");
```

Getting below error, which is also not expected because we are not setting memory `20GB`. Whatever size value I set, it will always give me same below error. I have also debugged the code and it seems `setMemorySizeInMb` is not passing with request at all.

```
Exception in thread "main" com.myjeeva.digitalocean.exception.DigitalOceanException: Cannot create a droplet with a smaller disk (20GB) than the image (40GB).
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.evaluateResponse(DigitalOceanClient.java:1589)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.executeHttpRequest(DigitalOceanClient.java:1534)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.doPost(DigitalOceanClient.java:1494)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.perform(DigitalOceanClient.java:1451)
	at com.myjeeva.digitalocean.impl.DigitalOceanClient.createDroplet(DigitalOceanClient.java:306)
```

**Comment by jeevatkm** [comment] 2017-07-10 17:32
Actually this behaviour is not expected, As per DO [create droplet](https://developers.digitalocean.com/documentation/v2/#create-a-new-droplet). Following structure of payload is expected by server.

```json
{
  "name": "example.com",
  "region": "nyc3",
  "size": "512mb",
  "image": "ubuntu-14-04-x64",
  "ssh_keys": null,
  "backups": false,
  "ipv6": true,
  "user_data": null,
  "private_networking": null,
  "volumes": null,
  "tags": [
    "web"
  ]
}
```

If you look at [DropletSerializer](https://github.com/jeevatkm/digitalocean-api-java/blob/master/src/main/java/com/myjeeva/digitalocean/serializer/DropletSerializer.java) class, you will see all the required elements are sent in the request.

`setMemorySizeInMb` is not part of the request payload. Please refer these test cases [testCreateDropletByImageId](https://github.com/jeevatkm/digitalocean-api-java/blob/master/src/test/java/com/myjeeva/digitalocean/DigitalOceanIntegrationTest.java#L186), [testCreateDropletByImageSlug](https://github.com/jeevatkm/digitalocean-api-java/blob/master/src/test/java/com/myjeeva/digitalocean/DigitalOceanIntegrationTest.java#L220) and try.

Let me know your outcome.

**Comment by vishalzanzrukia** [comment] 2017-07-10 17:47
Hi @jeevatkm ,

You are right, I realized the same after I posted this one, but I have couple of questions if you don't mind.

- Where is mapping defined between `imageId` and actual distribution used? (i.e. [testCreateDropletByImageId](https://github.com/jeevatkm/digitalocean-api-java/blob/master/src/test/java/com/myjeeva/digitalocean/DigitalOceanIntegrationTest.java#L186)
- How DO defined the disk size, because it's not taking in request? Is there any mapping between disk size and memory size?

Thanks in advance.

Regards,
Vishal Z.

**Comment by jeevatkm** [comment] 2017-07-10 18:30
DO provides predefined set of Droplet options to choose. Refer this [page](https://www.digitalocean.com/pricing/#droplet) for that.

Typically it is based on Memory size.

----

- ImageId is used when you have snapshot of existing droplet and you create from it.
- Image Slug is used when you create a fresh droplet with selected distribution. Refer to [testCreateDropletByImageSlug](https://github.com/jeevatkm/digitalocean-api-java/blob/master/src/test/java/com/myjeeva/digitalocean/DigitalOceanIntegrationTest.java#L220). Typically you use image slug returned by DO via method `getAvailableImages`

**Comment by jeevatkm** [comment] 2017-07-10 18:30
Not a bug, closing it.

**Closed by jeevatkm** 2017-07-10 18:30 UTC
Labels: analysis
