### ISSUE TITLE
DigitalOceanClient hangs on retry

### ISSUE THREAD

**Issue by maddie** [jeevatkm/digitalocean-api-java#40] opened 2015-10-17 04:06 UTC
I wrote an in-house web application based on Spring Framework, and one of the component is a `@Scheduled` job that runs periodically to update the droplet statuses.

It hanged after a retry, so I added some debug logs into the code. Normally it would be like this:
```
11:38:34,341 INFO  [stdout] (myScheduler-3) Got DO client
11:38:35,574 INFO  [stdout] (myScheduler-3) Got droplet info.
11:38:35,575 INFO  [stdout] (myScheduler-3) Got droplet status.
11:38:35,575 INFO  [stdout] (myScheduler-3) Setting droplet status: Active
11:38:35,576 INFO  [stdout] (myScheduler-3) Updating droplet info to database.
11:38:35,576 INFO  [stdout] (myScheduler-3) Updating info for droplet: 8249784
```
It's a for loop that loops all droplets I've recorded in the local database.

But before it hangs, it would show logs like this:
```
11:38:35,579 INFO  [stdout] (myScheduler-3) Got DO client
11:42:26,054 INFO  [org.apache.http.impl.execchain.RetryExec] (myScheduler-3) I/O exception (java.net.SocketException) caught when processing request to {s}->https://api.digitalocean.com:443: Connection reset
11:42:26,054 INFO  [org.apache.http.impl.execchain.RetryExec] (myScheduler-3) Retrying request to {s}->https://api.digitalocean.com:443
```
And nothing else happens.

Since I set the scheduler to fixedDelay = duration, the scheduler won't be executed again unless the last execution is completed. The problem above prevents the scheduler to work properly.

Is there any workaround for this problem?

**Comment by maddie** [comment] 2015-10-17 05:43
Partial code: 
```
                System.out.println("Updating info for droplet: " + dropletId);
                String authKey = "xxxxx";
                DigitalOcean apiClient = getClient(authKey);
                System.out.println("Got DO client");

                Droplet droplet = apiClient.getDropletInfo(dropletId);
                System.out.println("Got droplet info.");
                DropletStatus status = droplet.getStatus();
                System.out.println("Got droplet status.");
                try {
                    String ip = (droplet.getNetworks().getVersion4Networks().get(0).getIpAddress());
                    System.out.println("Got droplet IP address.");
                } catch (NullPointerException e) {
                    System.out.println("IP Address not yet available for droplet " + dropletId);
                }
                System.out.println("Setting droplet status: " + statusStr);
                save(droplet);
                System.out.println("Updating droplet info to database.");
```

**Comment by jeevatkm** [comment] 2015-10-19 19:14
Will analyze and let you know.

**Comment by maddie** [comment] 2015-10-22 15:04
Alright, thanks!

**Comment by adpande** [comment] 2016-01-13 10:47
Hi @jeevatkm ,

We are also facing the same issue when client hangs in between. Here is the line on which it hangs:

apiClient = new DigitalOceanClient("v2", token);

Thanks in advance for the help.

Regards,
Abhishek

**Comment by jeevatkm** [comment] 2016-06-06 18:22
@adpande DigitalOcean has v2 API active as of now. v1 is already sunsetted.

**Comment by jeevatkm** [comment] 2016-06-06 18:23
@maddie I couldn't reproduce at my end. I guess it is specific to your use case. Can you help me to reproduce it?

**Comment by jeevatkm** [comment] 2016-06-12 23:16
Closing it for v2.5 release.

**Closed by jeevatkm** 2016-06-12 23:16 UTC
Labels: analysis
